# Generated by Django 6.0.5 on 2026-05-14 23:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("slug", models.SlugField(unique=True)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("dell", "Dell"),
                            ("hp", "HP"),
                            ("supermicro", "Supermicro"),
                            ("rpi", "Raspberry Pi"),
                            ("macmini", "Mac Mini"),
                            ("whitebox", "Whitebox"),
                            ("mystery", "Mystery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("1u", "1U"),
                            ("2u", "2U"),
                            ("4u", "4U"),
                            ("sff", "Small Form Factor"),
                            ("tower", "Full Tower"),
                            ("palm", "Palm-Sized"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("she", "She/Her"),
                            ("he", "He/Him"),
                            ("they", "They/Them"),
                            ("complicated", "It's Complicated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("age_years", models.PositiveSmallIntegerField()),
                (
                    "arrival_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("on_hold", "On Hold"),
                            ("adopted", "Adopted"),
                            ("foster", "In Foster Care"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("adoption_fee_cents", models.PositiveIntegerField(default=0)),
                ("backstory", models.TextField()),
                (
                    "personality",
                    models.CharField(
                        help_text="Comma-separated traits", max_length=255
                    ),
                ),
                ("special_needs", models.CharField(blank=True, max_length=255)),
                ("portrait", models.ImageField(blank=True, upload_to="portraits/")),
                ("is_featured", models.BooleanField(default=False)),
                ("adopted_by_name", models.CharField(blank=True, max_length=120)),
                ("adopted_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="AdoptionApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("applicant_name", models.CharField(max_length=120)),
                ("applicant_email", models.EmailField(max_length=254)),
                ("applicant_location", models.CharField(max_length=160)),
                ("has_stable_power", models.BooleanField()),
                (
                    "decibel_tolerance",
                    models.CharField(
                        choices=[
                            ("quiet", "Whisper-quiet only"),
                            ("medium", "A gentle hum is fine"),
                            ("loud", "I love the sound of spinning fans"),
                        ],
                        max_length=20,
                    ),
                ),
                ("other_servers_present", models.CharField(blank=True, max_length=255)),
                ("why_this_server", models.TextField()),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="shelter.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
