# Generated by Django 6.0.5 on 2026-05-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='has_stable_power',
        ),
    ]
