# Generated by Django 6.0.5 on 2026-05-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_remove_has_stable_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerPortrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.BinaryField()),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('mimetype', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='shelter.ServerPortrait/bytes/filename/mimetype'),
        ),
    ]
