services:
  demo:
    build:
      platforms:
        - linux/amd64
    environment:
      WORKERS: 2
    volumes:
      - db:/app/db
      - media:/app/media
    x-ports:
      - 8000/https
    x-pre_deploy:
      command: python manage.py migrate

volumes:
  db:
  media:
